services:
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"  # Exposes Spring Boot app on port 8080
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "5137:5137" # Exposes the frontend on 5137 
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://backend:8080/api
    depends_on:
      - backend

  database:
    image: postgres:15
    ports:
      - "5432:5432" # Exposes database on port 5432
    networks:
      - app-network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: financialapp
    volumes:
      - db-data:/var/lib/postgresql/data # Persist the database data
networks:
  app-network:
    driver: bridge

volumes:
  db-data:
