version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"  # Exposes Spring Boot app on port 8080
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "5137:5137"     
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://backend:8080/api
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
